package com.gmself.bingobingo.module.subject.db.dao;


import com.gmself.bingobingo.module.subject.entity.City;
import org.springframework.stereotype.Repository;

@Repository
public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated
     */
    int insertSelective(City record);
}