package com.gmself.bingobingo.module.subject.db.dao;

import com.gmself.bingobingo.module.subject.entity.User;
import org.springframework.stereotype.Repository;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    int updateByPhoneNumber(User user);

    int updateByDeviceID(User user);

    User selectByDeviceID(String deviceID);

    User selectByPhoneNumber(String phoneNumber);

    String selectPhoneNumberByDeviceID(String deviceID);

    String selectDeviceIDByPhoneNumber(String phoneNumber);

    String selectTokenByDeviceID(String deviceID);
}