package com.gmself.bingobingo.module.subject.db.dao;

import com.gmself.bingobingo.module.subject.entity.Weather;
import org.springframework.stereotype.Repository;

@Repository
public interface WeatherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated
     */
    int insert(Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated
     */
    int insertSelective(Weather record);
}