package com.gmself.bingobingo.function.statistics;

import com.gmself.bingobingo.function.statistics.entity.UserLocationStatistics;
import org.springframework.stereotype.Repository;

@Repository
public interface UserLocationStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_location_statistics
     *
     * @mbggenerated
     */
    int insert(UserLocationStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_location_statistics
     *
     * @mbggenerated
     */
    int insertSelective(UserLocationStatistics record);

    UserLocationStatistics selectByLocationID(String locationId);

    int updateByLocationID(UserLocationStatistics record);
}