package com.gmself.bingobingo.db.dao;

import com.gmself.bingobingo.db.entity.HfWeatherNow;

public interface HfWeatherNowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_weather_now
     *
     * @mbggenerated
     */
    int insert(HfWeatherNow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_weather_now
     *
     * @mbggenerated
     */
    int insertSelective(HfWeatherNow record);
}