package com.gmself.bingobingo.module.subject.entity;

import org.apache.ibatis.type.Alias;
import org.springframework.stereotype.Component;

@Component("city")
@Alias(value = "city")
public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.coun_name
     *
     * @mbggenerated
     */
    private String counName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.parent_name
     *
     * @mbggenerated
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.mojitianqi_city_id
     *
     * @mbggenerated
     */
    private Integer mojitianqiCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.timezone
     *
     * @mbggenerated
     */
    private Integer timezone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.id
     *
     * @return the value of city.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.id
     *
     * @param id the value for city.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_id
     *
     * @return the value of city.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_id
     *
     * @param cityId the value for city.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.city_name
     *
     * @return the value of city.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.city_name
     *
     * @param cityName the value for city.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.coun_name
     *
     * @return the value of city.coun_name
     *
     * @mbggenerated
     */
    public String getCounName() {
        return counName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.coun_name
     *
     * @param counName the value for city.coun_name
     *
     * @mbggenerated
     */
    public void setCounName(String counName) {
        this.counName = counName == null ? null : counName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.parent_name
     *
     * @return the value of city.parent_name
     *
     * @mbggenerated
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.parent_name
     *
     * @param parentName the value for city.parent_name
     *
     * @mbggenerated
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.mojitianqi_city_id
     *
     * @return the value of city.mojitianqi_city_id
     *
     * @mbggenerated
     */
    public Integer getMojitianqiCityId() {
        return mojitianqiCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.mojitianqi_city_id
     *
     * @param mojitianqiCityId the value for city.mojitianqi_city_id
     *
     * @mbggenerated
     */
    public void setMojitianqiCityId(Integer mojitianqiCityId) {
        this.mojitianqiCityId = mojitianqiCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.timezone
     *
     * @return the value of city.timezone
     *
     * @mbggenerated
     */
    public Integer getTimezone() {
        return timezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.timezone
     *
     * @param timezone the value for city.timezone
     *
     * @mbggenerated
     */
    public void setTimezone(Integer timezone) {
        this.timezone = timezone;
    }
}