package com.gmself.bingobingo.module.subject.entity;

import org.apache.ibatis.type.Alias;
import org.springframework.stereotype.Component;

@Component("user")
@Alias(value = "user")
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name_
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone_number_
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_date_
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.replace_date_
     *
     * @mbggenerated
     */
    private String replaceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_location_id_
     *
     * @mbggenerated
     */
    private String lastLocationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name_
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.signature_
     *
     * @mbggenerated
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex_
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id_
     *
     * @return the value of user.id_
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id_
     *
     * @param id the value for user.id_
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name_
     *
     * @return the value of user.name_
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name_
     *
     * @param name the value for user.name_
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone_number_
     *
     * @return the value of user.phone_number_
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone_number_
     *
     * @param phoneNumber the value for user.phone_number_
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_date_
     *
     * @return the value of user.create_date_
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_date_
     *
     * @param createDate the value for user.create_date_
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.replace_date_
     *
     * @return the value of user.replace_date_
     *
     * @mbggenerated
     */
    public String getReplaceDate() {
        return replaceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.replace_date_
     *
     * @param replaceDate the value for user.replace_date_
     *
     * @mbggenerated
     */
    public void setReplaceDate(String replaceDate) {
        this.replaceDate = replaceDate == null ? null : replaceDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_location_id_
     *
     * @return the value of user.last_location_id_
     *
     * @mbggenerated
     */
    public String getLastLocationId() {
        return lastLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_location_id_
     *
     * @param lastLocationId the value for user.last_location_id_
     *
     * @mbggenerated
     */
    public void setLastLocationId(String lastLocationId) {
        this.lastLocationId = lastLocationId == null ? null : lastLocationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_
     *
     * @return the value of user.email_
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_
     *
     * @param email the value for user.email_
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name_
     *
     * @return the value of user.nick_name_
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name_
     *
     * @param nickName the value for user.nick_name_
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.signature_
     *
     * @return the value of user.signature_
     *
     * @mbggenerated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.signature_
     *
     * @param signature the value for user.signature_
     *
     * @mbggenerated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex_
     *
     * @return the value of user.sex_
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex_
     *
     * @param sex the value for user.sex_
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }
}