package com.gmself.bingobingo.module.subject.entity;

import org.apache.ibatis.type.Alias;
import org.springframework.stereotype.Component;

import java.util.Date;

@Component("weather")
@Alias(value = "weather")
public class Weather {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.predict_date
     *
     * @mbggenerated
     */
    private Date predictDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.condition_day
     *
     * @mbggenerated
     */
    private String conditionDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.condition_id_day
     *
     * @mbggenerated
     */
    private String conditionIdDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.condition_id_night
     *
     * @mbggenerated
     */
    private String conditionIdNight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.condition_night
     *
     * @mbggenerated
     */
    private String conditionNight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.temp_day
     *
     * @mbggenerated
     */
    private String tempDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.temp_night
     *
     * @mbggenerated
     */
    private String tempNight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.wind_dir_day
     *
     * @mbggenerated
     */
    private String windDirDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.wind_dir_night
     *
     * @mbggenerated
     */
    private String windDirNight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.wind_level_day
     *
     * @mbggenerated
     */
    private String windLevelDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather.wind_level_night
     *
     * @mbggenerated
     */
    private String windLevelNight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.id
     *
     * @return the value of weather.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.id
     *
     * @param id the value for weather.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.city_id
     *
     * @return the value of weather.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.city_id
     *
     * @param cityId the value for weather.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.predict_date
     *
     * @return the value of weather.predict_date
     *
     * @mbggenerated
     */
    public Date getPredictDate() {
        return predictDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.predict_date
     *
     * @param predictDate the value for weather.predict_date
     *
     * @mbggenerated
     */
    public void setPredictDate(Date predictDate) {
        this.predictDate = predictDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.condition_day
     *
     * @return the value of weather.condition_day
     *
     * @mbggenerated
     */
    public String getConditionDay() {
        return conditionDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.condition_day
     *
     * @param conditionDay the value for weather.condition_day
     *
     * @mbggenerated
     */
    public void setConditionDay(String conditionDay) {
        this.conditionDay = conditionDay == null ? null : conditionDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.condition_id_day
     *
     * @return the value of weather.condition_id_day
     *
     * @mbggenerated
     */
    public String getConditionIdDay() {
        return conditionIdDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.condition_id_day
     *
     * @param conditionIdDay the value for weather.condition_id_day
     *
     * @mbggenerated
     */
    public void setConditionIdDay(String conditionIdDay) {
        this.conditionIdDay = conditionIdDay == null ? null : conditionIdDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.condition_id_night
     *
     * @return the value of weather.condition_id_night
     *
     * @mbggenerated
     */
    public String getConditionIdNight() {
        return conditionIdNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.condition_id_night
     *
     * @param conditionIdNight the value for weather.condition_id_night
     *
     * @mbggenerated
     */
    public void setConditionIdNight(String conditionIdNight) {
        this.conditionIdNight = conditionIdNight == null ? null : conditionIdNight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.condition_night
     *
     * @return the value of weather.condition_night
     *
     * @mbggenerated
     */
    public String getConditionNight() {
        return conditionNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.condition_night
     *
     * @param conditionNight the value for weather.condition_night
     *
     * @mbggenerated
     */
    public void setConditionNight(String conditionNight) {
        this.conditionNight = conditionNight == null ? null : conditionNight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.temp_day
     *
     * @return the value of weather.temp_day
     *
     * @mbggenerated
     */
    public String getTempDay() {
        return tempDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.temp_day
     *
     * @param tempDay the value for weather.temp_day
     *
     * @mbggenerated
     */
    public void setTempDay(String tempDay) {
        this.tempDay = tempDay == null ? null : tempDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.temp_night
     *
     * @return the value of weather.temp_night
     *
     * @mbggenerated
     */
    public String getTempNight() {
        return tempNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.temp_night
     *
     * @param tempNight the value for weather.temp_night
     *
     * @mbggenerated
     */
    public void setTempNight(String tempNight) {
        this.tempNight = tempNight == null ? null : tempNight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.update_time
     *
     * @return the value of weather.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.update_time
     *
     * @param updateTime the value for weather.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.wind_dir_day
     *
     * @return the value of weather.wind_dir_day
     *
     * @mbggenerated
     */
    public String getWindDirDay() {
        return windDirDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.wind_dir_day
     *
     * @param windDirDay the value for weather.wind_dir_day
     *
     * @mbggenerated
     */
    public void setWindDirDay(String windDirDay) {
        this.windDirDay = windDirDay == null ? null : windDirDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.wind_dir_night
     *
     * @return the value of weather.wind_dir_night
     *
     * @mbggenerated
     */
    public String getWindDirNight() {
        return windDirNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.wind_dir_night
     *
     * @param windDirNight the value for weather.wind_dir_night
     *
     * @mbggenerated
     */
    public void setWindDirNight(String windDirNight) {
        this.windDirNight = windDirNight == null ? null : windDirNight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.wind_level_day
     *
     * @return the value of weather.wind_level_day
     *
     * @mbggenerated
     */
    public String getWindLevelDay() {
        return windLevelDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.wind_level_day
     *
     * @param windLevelDay the value for weather.wind_level_day
     *
     * @mbggenerated
     */
    public void setWindLevelDay(String windLevelDay) {
        this.windLevelDay = windLevelDay == null ? null : windLevelDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather.wind_level_night
     *
     * @return the value of weather.wind_level_night
     *
     * @mbggenerated
     */
    public String getWindLevelNight() {
        return windLevelNight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather.wind_level_night
     *
     * @param windLevelNight the value for weather.wind_level_night
     *
     * @mbggenerated
     */
    public void setWindLevelNight(String windLevelNight) {
        this.windLevelNight = windLevelNight == null ? null : windLevelNight.trim();
    }
}