package com.gmself.bingobingo.function.weather.entity;

import org.apache.ibatis.type.Alias;
import org.springframework.stereotype.Component;

@Component("hfWeatherNow")
@Alias(value = "hfWeatherNow")
public class HfWeatherNow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.id_
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.city_id_
     *
     * @mbggenerated
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.update_time_
     *
     * @mbggenerated
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.fl_
     *
     * @mbggenerated
     */
    private String fl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.tmp_
     *
     * @mbggenerated
     */
    private String tmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.cond_code_
     *
     * @mbggenerated
     */
    private String condCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.cond_txt_
     *
     * @mbggenerated
     */
    private String condTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.wind_deg_
     *
     * @mbggenerated
     */
    private String windDeg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.wind_dir_
     *
     * @mbggenerated
     */
    private String windDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.wind_sc_
     *
     * @mbggenerated
     */
    private String windSc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.wind_spd_
     *
     * @mbggenerated
     */
    private String windSpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.hum_
     *
     * @mbggenerated
     */
    private String hum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.pcpn_
     *
     * @mbggenerated
     */
    private String pcpn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.pres_
     *
     * @mbggenerated
     */
    private String pres;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.vis_
     *
     * @mbggenerated
     */
    private String vis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_weather_now.cloud_
     *
     * @mbggenerated
     */
    private String cloud;

    public HfWeatherNow(String cityId, String updateTime) {
        this.cityId = cityId;
        this.updateTime = updateTime;
    }

    public HfWeatherNow() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.id_
     *
     * @return the value of hf_weather_now.id_
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.id_
     *
     * @param id the value for hf_weather_now.id_
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.city_id_
     *
     * @return the value of hf_weather_now.city_id_
     *
     * @mbggenerated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.city_id_
     *
     * @param cityId the value for hf_weather_now.city_id_
     *
     * @mbggenerated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.update_time_
     *
     * @return the value of hf_weather_now.update_time_
     *
     * @mbggenerated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.update_time_
     *
     * @param updateTime the value for hf_weather_now.update_time_
     *
     * @mbggenerated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.fl_
     *
     * @return the value of hf_weather_now.fl_
     *
     * @mbggenerated
     */
    public String getFl() {
        return fl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.fl_
     *
     * @param fl the value for hf_weather_now.fl_
     *
     * @mbggenerated
     */
    public void setFl(String fl) {
        this.fl = fl == null ? null : fl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.tmp_
     *
     * @return the value of hf_weather_now.tmp_
     *
     * @mbggenerated
     */
    public String getTmp() {
        return tmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.tmp_
     *
     * @param tmp the value for hf_weather_now.tmp_
     *
     * @mbggenerated
     */
    public void setTmp(String tmp) {
        this.tmp = tmp == null ? null : tmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.cond_code_
     *
     * @return the value of hf_weather_now.cond_code_
     *
     * @mbggenerated
     */
    public String getCondCode() {
        return condCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.cond_code_
     *
     * @param condCode the value for hf_weather_now.cond_code_
     *
     * @mbggenerated
     */
    public void setCondCode(String condCode) {
        this.condCode = condCode == null ? null : condCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.cond_txt_
     *
     * @return the value of hf_weather_now.cond_txt_
     *
     * @mbggenerated
     */
    public String getCondTxt() {
        return condTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.cond_txt_
     *
     * @param condTxt the value for hf_weather_now.cond_txt_
     *
     * @mbggenerated
     */
    public void setCondTxt(String condTxt) {
        this.condTxt = condTxt == null ? null : condTxt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.wind_deg_
     *
     * @return the value of hf_weather_now.wind_deg_
     *
     * @mbggenerated
     */
    public String getWindDeg() {
        return windDeg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.wind_deg_
     *
     * @param windDeg the value for hf_weather_now.wind_deg_
     *
     * @mbggenerated
     */
    public void setWindDeg(String windDeg) {
        this.windDeg = windDeg == null ? null : windDeg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.wind_dir_
     *
     * @return the value of hf_weather_now.wind_dir_
     *
     * @mbggenerated
     */
    public String getWindDir() {
        return windDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.wind_dir_
     *
     * @param windDir the value for hf_weather_now.wind_dir_
     *
     * @mbggenerated
     */
    public void setWindDir(String windDir) {
        this.windDir = windDir == null ? null : windDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.wind_sc_
     *
     * @return the value of hf_weather_now.wind_sc_
     *
     * @mbggenerated
     */
    public String getWindSc() {
        return windSc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.wind_sc_
     *
     * @param windSc the value for hf_weather_now.wind_sc_
     *
     * @mbggenerated
     */
    public void setWindSc(String windSc) {
        this.windSc = windSc == null ? null : windSc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.wind_spd_
     *
     * @return the value of hf_weather_now.wind_spd_
     *
     * @mbggenerated
     */
    public String getWindSpd() {
        return windSpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.wind_spd_
     *
     * @param windSpd the value for hf_weather_now.wind_spd_
     *
     * @mbggenerated
     */
    public void setWindSpd(String windSpd) {
        this.windSpd = windSpd == null ? null : windSpd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.hum_
     *
     * @return the value of hf_weather_now.hum_
     *
     * @mbggenerated
     */
    public String getHum() {
        return hum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.hum_
     *
     * @param hum the value for hf_weather_now.hum_
     *
     * @mbggenerated
     */
    public void setHum(String hum) {
        this.hum = hum == null ? null : hum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.pcpn_
     *
     * @return the value of hf_weather_now.pcpn_
     *
     * @mbggenerated
     */
    public String getPcpn() {
        return pcpn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.pcpn_
     *
     * @param pcpn the value for hf_weather_now.pcpn_
     *
     * @mbggenerated
     */
    public void setPcpn(String pcpn) {
        this.pcpn = pcpn == null ? null : pcpn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.pres_
     *
     * @return the value of hf_weather_now.pres_
     *
     * @mbggenerated
     */
    public String getPres() {
        return pres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.pres_
     *
     * @param pres the value for hf_weather_now.pres_
     *
     * @mbggenerated
     */
    public void setPres(String pres) {
        this.pres = pres == null ? null : pres.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.vis_
     *
     * @return the value of hf_weather_now.vis_
     *
     * @mbggenerated
     */
    public String getVis() {
        return vis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.vis_
     *
     * @param vis the value for hf_weather_now.vis_
     *
     * @mbggenerated
     */
    public void setVis(String vis) {
        this.vis = vis == null ? null : vis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_weather_now.cloud_
     *
     * @return the value of hf_weather_now.cloud_
     *
     * @mbggenerated
     */
    public String getCloud() {
        return cloud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_weather_now.cloud_
     *
     * @param cloud the value for hf_weather_now.cloud_
     *
     * @mbggenerated
     */
    public void setCloud(String cloud) {
        this.cloud = cloud == null ? null : cloud.trim();
    }
}