package com.gmself.bingobingo.function.weather;

import com.gmself.bingobingo.function.weather.entity.HfCity;
import org.springframework.stereotype.Repository;

@Repository
public interface HfCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_city
     *
     * @mbggenerated
     */
    int insert(HfCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_city
     *
     * @mbggenerated
     */
    int insertSelective(HfCity record);
}