package com.gmself.bingobingo.function.weather;

import com.gmself.bingobingo.function.weather.entity.HfWeatherNow;
import org.springframework.stereotype.Repository;

@Repository
public interface HfWeatherNowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_weather_now
     *
     * @mbggenerated
     */
    int insertNow(HfWeatherNow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_weather_now
     *
     * @mbggenerated
     */
    int insertNowSelective(HfWeatherNow record);

    HfWeatherNow selectNowByCityID(String cityId);

    int updateNow(HfWeatherNow weatherNow);

}