package com.gmself.bingobingo.function.weather;

import com.gmself.bingobingo.function.weather.entity.HFWeatherForecast;
import org.springframework.stereotype.Repository;

@Repository
public interface HFWeatherForecastMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated
     */
    int insertForecast(HFWeatherForecast weather);

    int updateForecast(HFWeatherForecast record);

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table weather
//     *
//     * @mbggenerated
//     */
//    int insertSelective(Weather record);
//
//    Weather selectByPredictDate(String predictDate);
//


}