package com.gmself.bingobingo.function.weather;

import com.gmself.bingobingo.function.weather.entity.HFWeatherForecast;
import org.springframework.stereotype.Repository;

import java.util.HashMap;
import java.util.List;

@Repository
public interface HFWeatherForecastMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weather
     *
     * @mbggenerated
     */
    int insertForecast(HFWeatherForecast weather);

    int updateForecast(HFWeatherForecast record);

    /**
     * @param map need with cityID and date
     *  date is weather from day
     * */
    List<HFWeatherForecast> selectByCityID(HashMap map);

//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table weather
//     *
//     * @mbggenerated
//     */
//    int insertSelective(Weather record);
//
//    Weather selectByPredictDate(String predictDate);
//


}